### PR TITLE
fix(co15): error when payload is too small

### LINKED ISSUE #194: bug(ot): co15 doesnt enforce correct ot count
Suppose, the receiver queues 60 OTs.
Suppose in `receive` the length of `SenderPayload` is 30.

Why is it not an error that the receiver will get only 30 OTs out of the 60 that they intended to receive?

_Originally posted by @themighty1 in https://github.com/privacy-scaling-explorations/mpz/pull/186#discussion_r1867807280_

### PR DESCRIPTION
**Pull request by themighty1**
This PR handles cases when co15 sender's payload is too small.

Closes https://github.com/privacy-scaling-explorations/mpz/issues/194

### CODE REVIEW

File: crates/ot-core/src/chou_orlandi/receiver.rs [hunk 1]
```diff
@@ -140,6 +140,11 @@ impl Receiver<state::Setup> {
                 payload.len(),
             ));
         }
+        // Check that all queued transfers can be processed.
+        let total_queued = self.queue.iter().map(|q| q.count).sum();
+        if total_queued > payload.len() {
+            return Err(ReceiverError::PayloadTooSmall(total_queued, payload.len()));
+        }
```
Comment (sinui0) [inline crates/ot-core/src/chou_orlandi/receiver.rs]: Wouldn't it be equivalent to modify the above check to be `payload.len() != decryption_keys.len()`?

**Review by sinui0 — COMMENTED** [review]
Adding a test case would be good

**Comment by themighty1** [comment]
@sinui0 , ready for review

**Review by sinui0 — APPROVED** [review]
